webtalk_init -webtalk_dir C:/Users/Hp/PWM_GENERATION/PWM_GENERATION.sim/sim_1/behav/xsim/xsim.dir/PWM_TOP_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov  1 11:50:47 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "15150_4263_1558409712_125" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "edd8ae36-d692-46d6-ba1a-7ce47ca977e3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c0a022a1b183458d8af1a15df8b3fd35" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.27_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3726279095 -regid "15150_4263_1558409712_125" -xml C:/Users/Hp/PWM_GENERATION/PWM_GENERATION.sim/sim_1/behav/xsim/xsim.dir/PWM_TOP_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Hp/PWM_GENERATION/PWM_GENERATION.sim/sim_1/behav/xsim/xsim.dir/PWM_TOP_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Hp/PWM_GENERATION/PWM_GENERATION.sim/sim_1/behav/xsim/xsim.dir/PWM_TOP_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
